return {
    warmthRatingMultiplier = 5,
    coverageRatingMultiplier = 500,
    warmthRealMultiplier = 50,
    coverageRealMultiplier = 1.0,
    
    armorData = 
    {
        slotRatios = 
        {
            ["helmet"]          = 0.100,
            ["cuirass"]         = 0.200,
            ["leftPauldron"]    = 0.100,
            ["rightPauldron"]   = 0.100,
            ["greaves"]         = 0.150,
            ["boots"]           = 0.100,
            ["leftGauntlet"]    = 0.075,
            ["rightGauntlet"]   = 0.075,
            ["leftBracer"]      = 0.050,
            ["rightBracer"]     = 0.050,
        },
        --Warmth
        defaultWarmth = 10,
        warmthRatings = 
        {
            ["Adamantium "]     = 20,
            ["Bear "]           = 90,
            ["Bonemold "]       = 30,
            ["Chitin "]         = 30,
            ["Cloth "]          = 50,
            ["Colovian "]       = 60,
            ["Daedric "]        = 75,
            ["Dark B"]          = 35,
            ["Dreugh "]         = 30,
            ["Dwemer "]         = 20,
            ["Ebony "]          = 35,
            ["Glass " ]         = 05,
            ["Gondolier"]       = 20,
            ["Her Hand" ]       = 30,
            ["Ice Armor "]      = 0,
            ["Imperial Chain"]  = 30,
            ["Imperial Silv"]   = 40,
            ["Imperial Steel"]  = 40,
            ["Imperial Templ "] = 45,
            ["Indoril "]        = 40,
            ["Iron "]           = 30,
            ["Netch "]          = 45,
            ["Nordic Fur "]     = 30,
            ["Nordic Mail"]     = 55,
            ["Nordic Troll"]    = 50,
            ["Nordic Iron"]     = 45,
            ["Nordic leather"]  = 65,
            ["Orcich"]          = 30,
            ["Redoran"]         = 30,
            ["Royal G"]         = 35,
            ["Slave"]           = 25,
            ["Steel"]           = 30,
            ["Telvanni "]       = 60,
            ["Wolf "]           = 95,
        },
        --Coverage
        defaultCoverage = 20,
        coverageRatings = 
        {
            ["Adamantium "]     = 70,
            ["Bear "]           = 45,
            ["Bonemold "]       = 65,
            ["Chitin "]         = 40,
            ["Cloth "]          = 25,
            ["Colovian "]       = 30,
            ["Daedric "]        = 70,
            ["Dark B"]          = 65,
            ["Dreugh "]         = 95,
            ["Dwemer "]         = 80,
            ["Ebony "]          = 85,
            ["Glass " ]         = 85,
            ["Gondolier"]       = 100,
            ["Her Hand" ]       = 60,
            ["Ice Armor "]      = 85,
            ["Imperial Chain"]  = 30,
            ["Imperial Silv"]   = 75,
            ["Imperial Steel"]  = 70,
            ["Imperial Templ "] = 70,
            ["Indoril "]        = 60,
            ["Iron "]           = 65,
            ["Netch "]          = 50,
            ["Nordic Fur "]     = 30,
            ["Nordic Mail"]     = 35,
            ["Nordic Troll"]    = 60,
            ["Nordic Iron"]     = 65,
            ["Nordic leather"]  = 55,
            ["Orcich"]          = 75,
            ["Redoran"]         = 60,
            ["Royal G"]         = 75,
            ["Slave"]           = 10,
            ["Steel"]           = 75,
            ["Telvanni "]       = 85,
            ["Wolf "]           = 35,
        }
    },
    clothingData = {
        slotRatios =  
        {
            ["pants"]       = 0.15,
            ["shoes"]       = 0.05,
            ["shirt"]       = 0.20,
            ["robe"]        = 0.30,
            ["rightGlove"]  = 0.075,
            ["leftGlove"]   = 0.075,
            ["skirt"]       = 0.15,
        },
        --Warmth
        defaultWarmth = 40,
        warmthRatings = 
        {
            ["Common "]         = 30,
            ["Expensive "]      = 50,
            ["Extravagant "]    = 70,
            ["Exquisite "]      = 90,
            ["Flame"]           = 100,
            ["Frost"]           = 95,
        },
         --Coverage
        defaultCoverage = 30,
        coverageRatings = {
            ["Common "]         = 30,
            ["Expensive "]      = 45,
            ["Extravagant "]    = 60,
            ["Exquisite "]      = 70,
        }
    }
}